minecraft_version=1.21.10
artifact_mc_version=1.21.9-1.21.10
minecraft_dependency=>=1.21.9 <=1.21.10
malilib_mc_version=1.21.10
malilib_version=0.26.7
malilib_dependency=>=0.26.7 <0.27.0
mod_menu_version=16.0.1
xaero_minimap_version=fabric-1.21.10-26.3.0
xaero_world_map_version=fabric-1.21.10-1.43.0
