minecraft_version=26.3
artifact_mc_version=26.3
minecraft_dependency=>=26.3 <26.4
malilib_mc_version=26.3
malilib_version=0.30.1
malilib_modrinth_version_id=DPcJACN6
malilib_dependency=>=0.30.1 <0.31.0
mod_menu_version=21.0.0-alpha.1
xaero_minimap_version=fabric-26.2-26.4.0
xaero_world_map_version=fabric-26.2-1.44.0
